services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    depends_on:
      - database

  database:
    image: postgres:13
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 5432:5432

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--config"
      - "./etc/ngrok.yml"
      - "--all"
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml
    ports:
      - 4041:3000

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certificate:/etc/nginx/certificate
    ports:
      - 443:443
    command: [ nginx-debug, '-g', 'daemon off;' ]
    depends_on:
      - frontend