services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - database
    volumes:
      - ./certificate:/etc/certificate

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    depends_on:
      - database

  database:
    image: postgres:13
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 5432:5432